=== Wander29/RDL_GestioneProgetto_n-1/Relazione_Tecnica_Android/RDL_INFORMATICA_Moroni_Luca/ESE/DTD.dtd
<!ELEMENT studenti (studente*)>
<!ELEMENT studente (libretto)>
<!ELEMENT libretto (nome, cognome, matricola, facolta, anno_c, esami*)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT cognome (#PCDATA)>
    <!ELEMENT matricola (#PCDATA)>
    <!ELEMENT facolta (#PCDATA)>
    <!ELEMENT anno_c (#PCDATA)>
    <!ELEMENT esami (voto, data, esame_sost, crediti, professore)>
        <!ELEMENT voto (#PCDATA)>
        <!ELEMENT data (#PCDATA)>
        <!ELEMENT esame_sost (#PCDATA)>
        <!ELEMENT crediti (#PCDATA)>
        <!ELEMENT professore (#PCDATA)>

<!ATTLIST esami
	lode (si|no) #REQUIRED
>
<!ATTLIST libretto
    fuori_c (si|no) #REQUIRED
>

=== Wander29/RDL_GestioneProgetto_n-1/Relazione_Tecnica_Android/RDL_INFORMATICA_Moroni_Luca/ESE/esercizio.xml
<?xml version="1.0"?>
<!DOCTYPE studenti SYSTEM "DTD.dtd">
<?xml-stylesheet type="text/css" href="style.css"?>
<studenti>
    <studente>
        <libretto fuori_c="si">
            <nome>Mario</nome>
            <cognome>Rossi</cognome>
            <matricola>12</matricola>
            <facolta>medicina</facolta>
            <anno_c>2</anno_c>
            <esami lode="si">
                <voto>30</voto>
                <data>10/02/17</data>
                <esame_sost>chirurgia</esame_sost>
                <crediti>9</crediti>
                <professore>C.Bartolomei</professore>
            </esami>
            <esami lode="no">
                <voto>24</voto>
                <data>15/02/17</data>
                <esame_sost>chimica</esame_sost>
                <crediti>9</crediti>
                <professore>F.Bartolomei</professore>
            </esami>
            <esami lode="si">
                <voto>30</voto>
                <data>30/02/17</data>
                <esame_sost>storia della chirurgia</esame_sost>
                <crediti>9</crediti>
                <professore>C.Strozzini</professore>
            </esami>
        </libretto>
    </studente>
    <studente>
        <libretto fuori_c="no">
            <nome>Luigi</nome>
            <cognome>Gattini</cognome>
            <matricola>22</matricola>
            <facolta>ingegneria</facolta>
            <anno_c>1</anno_c>
            <esami lode="no">
                <voto>23</voto>
                <data>23/03/12</data>
                <esame_sost>matematica</esame_sost>
                <crediti>5</crediti>
                <professore>G.Giubotti</professore>
            </esami>
        </libretto>
    </studente>
    <studente>
        <libretto fuori_c="no">
            <nome>Catia</nome>
            <cognome>Lee</cognome>
            <matricola>5</matricola>
            <facolta>Chimica</facolta>
            <anno_c>3</anno_c>
            <esami lode="si">
                <voto>24</voto>
                <data>12/12/12</data>
                <esame_sost>chimica</esame_sost>
                <crediti>5</crediti>
                <professore>G.Giacometti</professore>
            </esami>
        </libretto>
    </studente>
    <studente>
        <libretto fuori_c="no">
            <nome>Sara</nome>
            <cognome>Delfino</cognome>
            <matricola>33</matricola>
            <facolta>Ingegneria Informatica</facolta>
            <anno_c>2</anno_c>
            <esami lode="si">
                <voto>30</voto>
                <data>30/04/14</data>
                <esame_sost>fondamenti di informatica</esame_sost>
                <crediti>10</crediti>
                <professore>K.Arzulli</professore>
            </esami>
        </libretto>
    </studente>
    <studente>
        <libretto fuori_c="si">
            <nome>Claudio</nome>
            <cognome>Mappaselli</cognome>
            <matricola>55</matricola>
            <facolta>Filosofia</facolta>
            <anno_c>3</anno_c>
            <esami lode="no">
                <voto>28</voto>
                <data>12/01/16</data>
                <esame_sost>Lettere</esame_sost>
                <crediti>6</crediti>
                <professore>H.Hammerman</professore>
            </esami>
        </libretto>
    </studente>
    
</studenti>
